extends Node

@onready var fpsValue := $VBoxContainer/fpsBox/fpsValue
@onready var simSpeedValue := $VBoxContainer/simSpeedBox/simSpeedValue

func _ready():
	simSpeedValue.text = str(Engine.time_scale)

func _process(_delta):
	fpsValue.text = str(Engine.get_frames_per_second())
	if Input.is_action_just_pressed("speed_engine"):
		Engine.time_scale += 0.05
		simSpeedValue.text = str(Engine.time_scale)
		print(Engine.time_scale)
	
	if Input.is_action_just_pressed("slow_engine"):
		Engine.time_scale -= 0.05
		simSpeedValue.text = str(Engine.time_scale)
		print(Engine.time_scale)
